name: "Snowflake Terraform Demo Workflow"

on:
 push:
   branches:
     - main

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.10

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform plan
        id: plan
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_REGION: ${{ secrets.SNOWFLAKE_REGION }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: terraform plan
        
   #  - name: Terraform apply
   #    id: apply
   #    run: terraform apply -auto-approve
