name: "Snowflake Terraform Demo Workflow"

on:
 push:
   branches:
     - main

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.10

      - name: Terraform Init
        id: Init
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
	  SNOWFLAKE_REGION: ${{ secrets.SNOWFLAKE_REGION }}
        run:|
	    terraform Init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        
   #  - name: Terraform apply
   #    id: apply
   #    run: terraform apply -auto-approve
